spring.application.name=destinations

spring.datasource.url=jdbc:mysql://localhost:3306/destinations?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

admin.username=admin
admin.password=tajneheslo
# mvnw spring-boot:run -Dspring-boot.run.profiles=dev
